---
vault_addr: "http://localhost:8200"
vault_skip_verify: true
vault_unseal_keys_file: "{{ ansible_facts['user_dir'] }}/.vault_keys"
vault_unseal_keys: []
vault_auto_unseal: true
vault_unseal_retries: 3
vault_unseal_delay: 5
vault_key_threshold: 3
vault_force_unseal: false
