---
vault_addr: "http://localhost:8200"
vault_skip_verify: true
vault_root_token_file: "{{ ansible_facts['user_dir'] }}/.vault_root_token"
# Set to true to also seal standby nodes by restarting Vault (restart seals the process)
vault_seal_standbys_by_restart: false
# Command to run on standby nodes to seal by restart. Examples:
# Docker (test): "docker restart {{ inventory_hostname }}"
# Systemd: "systemctl restart vault"
vault_seal_restart_command: ""
